### ISSUE TITLE
transparent background

### ISSUE THREAD

**Issue by paolocalosso** [asamuzaK/sidebarTabs#331]
hello and thanks for this very cool addon of our  beloved browser.
i'm using it on different linux distros all with gnome as de but i cannot set a transparency effect in background: is it possibile? 
thanks in advance

**Comment by asamuzaK** [comment]
Unfortunately, the answer is no at this time.
Maybe in the future.
Depends on [1919718 - Enhance &lt;input type=color&gt; with alpha and colorspace=display-p3](https://bugzilla.mozilla.org/show_bug.cgi?id=1919718).

**Comment by asamuzaK** [comment]
I haven't tested, how about user style like:
```
:root {
--background-color: transparent;
}
```

**Comment by paolocalosso** [comment]
thank you for your reply, i have already tried that code and it doesn't seem to work.

**Comment by asamuzaK** [comment]
Seems working as expected.
![solid](https://github.com/user-attachments/assets/c769897c-15aa-4372-a737-c0b772d2f9c6)

![alpha](https://github.com/user-attachments/assets/2b6e3725-658a-4884-8186-0a155db3e305)

![gradient](https://github.com/user-attachments/assets/5a4fb126-466b-4a7d-9b91-0ace2deaacb9)

![transparent](https://github.com/user-attachments/assets/d39c21ab-be7c-427a-9e7d-f6500f35c7ef)

**Comment by asamuzaK** [comment]
Ah, 3rd one is a bit weird though...

**Comment by paolocalosso** [comment]
not working also disabling css customization. maybe some gnome theme issue? i'm going to try also with other gtk themes

![Screenshot from 2024-12-04 16-25-34](https://github.com/user-attachments/assets/ae83cdc3-db3a-4f02-91cc-57ef16bfcd4f)

**Comment by paolocalosso** [comment]
it seems to work if set background-color without 

```
:root {
  background-color: transparent;
}
```

**Comment by asamuzaK** [comment]
Then, it's a bug.

The cause seems to be that backgrounds are specified in shorthand in sidebar.css.
```` css
background: var(--background-color);
````

I'll change them to:
```` css
background-color: var(--background-color);
````

To avoid regression bugs caused by this fix, please change your user style as follows:
```` css
:root {
  --background-color: transparent;
  /* Also modify the following custom variables if necessary
  --background-hover-color:
  --background-hover-shadow:
  --background-selection-hover-color:
  */
  /* Or like this
  --background-hover-color: var(--background-hover-shadow);
  --background-selection-hover-color: var(--background-hover-shadow);
  */
}
/* This can be removed after the fix */
html, body, main {
  background-color: var(--background-color);
}
````
